version: '3'

services:
  frontend:
    container_name: frontend
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./frontend:.
    environment:
      - NODE_ENV=development
    command: npm start