version: '3'

services:
  frontend:
    container_name: frontend
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /var/lib/jenkins/workspace/5TWIN5-SkiStation/frontend:/usr/src/app
    environment:
      - NODE_ENV=development
    command: npm start